server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  session:
    redis:
      namespace: auth:session

  data:
    redis:
      host: localhost
      port: 6379
      password: parrotpass
      repositories:
        enabled: true

jwt:
  secret:
    key: RhLmWjKd9GqSpOz6oEiYcB5wZgH2yJ0Db22sDaaZseDNC3zKvtU9sP8VqT4uR1XnMfbAe7LQaZZufAZadZzdX
  access-token:
    plus-hour: 12
  refresh-token:
    plus-hour: 169 # 1주일
